/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachApplyRouteImport } from './routes/coach.apply'
import { Route as TraineeIndexRouteImport } from './routes/trainee.index'
import { Route as CoachBlockBlockIdRouteImport } from './routes/coach.block.$blockId'
import { Route as CoachStatsMetricRouteImport } from './routes/coach.stats.$metric'
import { Route as TraineeWorkoutWorkoutIdRouteImport } from './routes/trainee.workout.$workoutId'
import { Route as CoachStatsMetricIndexRouteImport } from './routes/coach.stats.$metric.index'
import { Route as CoachStatsMetricItemIdRouteImport } from './routes/coach.stats.$metric.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/admin/coaches',
  path: '/admin/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachApplyRoute = CoachApplyRouteImport.update({
  id: '/coach/apply',
  path: '/coach/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeIndexRoute = TraineeIndexRouteImport.update({
  id: '/trainee/',
  path: '/trainee/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachBlockBlockIdRoute = CoachBlockBlockIdRouteImport.update({
  id: '/coach/block/$blockId',
  path: '/coach/block/$blockId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachStatsMetricRoute = CoachStatsMetricRouteImport.update({
  id: '/coach/stats/$metric',
  path: '/coach/stats/$metric',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeWorkoutWorkoutIdRoute = TraineeWorkoutWorkoutIdRouteImport.update({
  id: '/trainee/workout/$workoutId',
  path: '/trainee/workout/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachStatsMetricIndexRoute = CoachStatsMetricIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachStatsMetricRoute,
} as any)
const CoachStatsMetricItemIdRoute = CoachStatsMetricItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => CoachStatsMetricRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/coach/apply': typeof CoachApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/trainee/': typeof TraineeIndexRoute
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/coach/stats/$metric': typeof CoachStatsMetricRouteWithChildren
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
  '/coach/stats/$metric/$itemId': typeof CoachStatsMetricItemIdRoute
  '/coach/stats/$metric/': typeof CoachStatsMetricIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/coach/apply': typeof CoachApplyRoute
  '/admin': typeof AdminIndexRoute
  '/coach': typeof CoachIndexRoute
  '/trainee': typeof TraineeIndexRoute
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
  '/coach/stats/$metric/$itemId': typeof CoachStatsMetricItemIdRoute
  '/coach/stats/$metric': typeof CoachStatsMetricIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/coach/apply': typeof CoachApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/trainee/': typeof TraineeIndexRoute
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/coach/stats/$metric': typeof CoachStatsMetricRouteWithChildren
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
  '/coach/stats/$metric/$itemId': typeof CoachStatsMetricItemIdRoute
  '/coach/stats/$metric/': typeof CoachStatsMetricIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/admin/coaches'
    | '/coach/apply'
    | '/admin/'
    | '/coach/'
    | '/trainee/'
    | '/coach/block/$blockId'
    | '/coach/stats/$metric'
    | '/trainee/workout/$workoutId'
    | '/coach/stats/$metric/$itemId'
    | '/coach/stats/$metric/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/admin/coaches'
    | '/coach/apply'
    | '/admin'
    | '/coach'
    | '/trainee'
    | '/coach/block/$blockId'
    | '/trainee/workout/$workoutId'
    | '/coach/stats/$metric/$itemId'
    | '/coach/stats/$metric'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/admin/coaches'
    | '/coach/apply'
    | '/admin/'
    | '/coach/'
    | '/trainee/'
    | '/coach/block/$blockId'
    | '/coach/stats/$metric'
    | '/trainee/workout/$workoutId'
    | '/coach/stats/$metric/$itemId'
    | '/coach/stats/$metric/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  CoachApplyRoute: typeof CoachApplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  TraineeIndexRoute: typeof TraineeIndexRoute
  CoachBlockBlockIdRoute: typeof CoachBlockBlockIdRoute
  CoachStatsMetricRoute: typeof CoachStatsMetricRouteWithChildren
  TraineeWorkoutWorkoutIdRoute: typeof TraineeWorkoutWorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/admin/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/apply': {
      id: '/coach/apply'
      path: '/coach/apply'
      fullPath: '/coach/apply'
      preLoaderRoute: typeof CoachApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/': {
      id: '/trainee/'
      path: '/trainee'
      fullPath: '/trainee/'
      preLoaderRoute: typeof TraineeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/block/$blockId': {
      id: '/coach/block/$blockId'
      path: '/coach/block/$blockId'
      fullPath: '/coach/block/$blockId'
      preLoaderRoute: typeof CoachBlockBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/stats/$metric': {
      id: '/coach/stats/$metric'
      path: '/coach/stats/$metric'
      fullPath: '/coach/stats/$metric'
      preLoaderRoute: typeof CoachStatsMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/workout/$workoutId': {
      id: '/trainee/workout/$workoutId'
      path: '/trainee/workout/$workoutId'
      fullPath: '/trainee/workout/$workoutId'
      preLoaderRoute: typeof TraineeWorkoutWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/stats/$metric/': {
      id: '/coach/stats/$metric/'
      path: '/'
      fullPath: '/coach/stats/$metric/'
      preLoaderRoute: typeof CoachStatsMetricIndexRouteImport
      parentRoute: typeof CoachStatsMetricRoute
    }
    '/coach/stats/$metric/$itemId': {
      id: '/coach/stats/$metric/$itemId'
      path: '/$itemId'
      fullPath: '/coach/stats/$metric/$itemId'
      preLoaderRoute: typeof CoachStatsMetricItemIdRouteImport
      parentRoute: typeof CoachStatsMetricRoute
    }
  }
}

interface CoachStatsMetricRouteChildren {
  CoachStatsMetricItemIdRoute: typeof CoachStatsMetricItemIdRoute
  CoachStatsMetricIndexRoute: typeof CoachStatsMetricIndexRoute
}

const CoachStatsMetricRouteChildren: CoachStatsMetricRouteChildren = {
  CoachStatsMetricItemIdRoute: CoachStatsMetricItemIdRoute,
  CoachStatsMetricIndexRoute: CoachStatsMetricIndexRoute,
}

const CoachStatsMetricRouteWithChildren =
  CoachStatsMetricRoute._addFileChildren(CoachStatsMetricRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  CoachApplyRoute: CoachApplyRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  TraineeIndexRoute: TraineeIndexRoute,
  CoachBlockBlockIdRoute: CoachBlockBlockIdRoute,
  CoachStatsMetricRoute: CoachStatsMetricRouteWithChildren,
  TraineeWorkoutWorkoutIdRoute: TraineeWorkoutWorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
