/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as TraineeRouteImport } from './routes/trainee'
import { Route as CoachBlockBlockIdRouteImport } from './routes/coach.block.$blockId'
import { Route as TraineeWorkoutWorkoutIdRouteImport } from './routes/trainee.workout.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeRoute = TraineeRouteImport.update({
  id: '/trainee',
  path: '/trainee',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachBlockBlockIdRoute = CoachBlockBlockIdRouteImport.update({
  id: '/block/$blockId',
  path: '/block/$blockId',
  getParentRoute: () => CoachRoute,
} as any)
const TraineeWorkoutWorkoutIdRoute = TraineeWorkoutWorkoutIdRouteImport.update({
  id: '/workout/$workoutId',
  path: '/workout/$workoutId',
  getParentRoute: () => TraineeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/trainee': typeof TraineeRouteWithChildren
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/trainee': typeof TraineeRouteWithChildren
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/trainee': typeof TraineeRouteWithChildren
  '/coach/block/$blockId': typeof CoachBlockBlockIdRoute
  '/trainee/workout/$workoutId': typeof TraineeWorkoutWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/trainee'
    | '/coach/block/$blockId'
    | '/trainee/workout/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/trainee'
    | '/coach/block/$blockId'
    | '/trainee/workout/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/trainee'
    | '/coach/block/$blockId'
    | '/trainee/workout/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  TraineeRoute: typeof TraineeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee': {
      id: '/trainee'
      path: '/trainee'
      fullPath: '/trainee'
      preLoaderRoute: typeof TraineeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/block/$blockId': {
      id: '/coach/block/$blockId'
      path: '/block/$blockId'
      fullPath: '/coach/block/$blockId'
      preLoaderRoute: typeof CoachBlockBlockIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/trainee/workout/$workoutId': {
      id: '/trainee/workout/$workoutId'
      path: '/workout/$workoutId'
      fullPath: '/trainee/workout/$workoutId'
      preLoaderRoute: typeof TraineeWorkoutWorkoutIdRouteImport
      parentRoute: typeof TraineeRoute
    }
  }
}

interface CoachRouteChildren {
  CoachBlockBlockIdRoute: typeof CoachBlockBlockIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachBlockBlockIdRoute: CoachBlockBlockIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface TraineeRouteChildren {
  TraineeWorkoutWorkoutIdRoute: typeof TraineeWorkoutWorkoutIdRoute
}

const TraineeRouteChildren: TraineeRouteChildren = {
  TraineeWorkoutWorkoutIdRoute: TraineeWorkoutWorkoutIdRoute,
}

const TraineeRouteWithChildren =
  TraineeRoute._addFileChildren(TraineeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  TraineeRoute: TraineeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
